import tensorflow as tf
var = tf.Variable([0.9,0.9])
var2 = tf.Variable([0.0,0.0])
var3 = tf.Variable([-1.,-1.])
copy_first_variable = var2.assign(var)
copy_third_variable = var.assign(var3)
init = tf.initialize_all_variables()
sess = tf.Session()

sess.run(init)
print("var 2:")
print(sess.run(var2))
sess.run(copy_first_variable)
print("var 2: (after copying from var 1)")
print(sess.run(var2))
print("update var 1")
sess.run(copy_third_variable)
print("var1: ",sess.run(var))
print("var2: ",sess.run(var2))